/**
 * PUNT FINANCE — Edge Middleware
 * ─────────────────────────────────────────────────────────────────────────────
 * Runs at the Vercel Edge Network before any route handler or RSC.
 *
 * Responsibilities:
 *   1. CSP Nonce generation    — cryptographic nonce per-request for script-src
 *   2. Security headers        — HSTS, X-Frame-Options, etc.
 *   3. Request ID              — for distributed tracing / log correlation
 *
 * Rate limiting is handled inside the Server Action (lib/ratelimit.ts)
 * rather than here, because:
 *   a) Server Action rate limiting can differentiate between cached and
 *      AI-generation requests with two separate limiters.
 *   b) Edge middleware runs on EVERY request including static assets —
 *      we only want to meter search requests.
 *   c) The @upstash/ratelimit SDK works in both Edge and Node runtimes.
 *
 * If you want an additional blanket edge-level DDoS guard, uncomment the
 * OPTIONAL EDGE RATE LIMIT section below.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { NextRequest, NextResponse } from "next/server";
import { randomBytes }               from "crypto";

/* ── Paths that should NOT be processed by this middleware ─────────────── */
const BYPASS_PATHS = [
  "/_next/static",
  "/_next/image",
  "/favicon.ico",
  "/apple-touch-icon",
  "/robots.txt",
  "/sitemap.xml",
];

function shouldBypass(pathname: string): boolean {
  return BYPASS_PATHS.some((prefix) => pathname.startsWith(prefix));
}

/* ── Middleware ─────────────────────────────────────────────────────────── */

export function middleware(request: NextRequest): NextResponse {
  const { pathname } = request.nextUrl;

  if (shouldBypass(pathname)) {
    return NextResponse.next();
  }

  /* ── 1. Generate a cryptographic nonce for this request ─────────────
     Used in the Content-Security-Policy header to allowlist inline scripts
     generated by Next.js itself, without using the dangerous 'unsafe-inline'.
     The nonce is threaded into layout.tsx via the x-nonce request header.  */
  const nonce = randomBytes(16).toString("base64");

  /* ── 2. Generate a request correlation ID ───────────────────────────
     Allows matching middleware logs → server logs → Upstash analytics
     for any given request.                                               */
  const requestId = randomBytes(8).toString("hex");

  /* ── 3. Build the response and set security headers ─────────────────
     We pass headers to the origin (x-nonce, x-request-id) and set
     response headers (CSP, HSTS, etc.) on the outbound response.        */
  const requestHeaders = new Headers(request.headers);
  requestHeaders.set("x-nonce",      nonce);
  requestHeaders.set("x-request-id", requestId);

  const response = NextResponse.next({
    request: { headers: requestHeaders },
  });

  /* ── 4. Content Security Policy ─────────────────────────────────────
     Production-grade CSP. The nonce is injected here so layout.tsx can
     thread it into the <script> tag without 'unsafe-inline'.
     
     Phase 2 additions vs Phase 1 static meta-tag CSP:
       • script-src now uses nonce instead of 'unsafe-inline'
       • connect-src permits Supabase and Upstash endpoints              */
  const csp = [
    "default-src 'self'",
    `script-src 'self' 'nonce-${nonce}'`,
    "style-src 'self' 'unsafe-inline'",   // Next.js needs this for CSS-in-JS
    "font-src 'self' data:",
    "img-src 'self' data: blob:",
    [
      "connect-src 'self'",
      process.env.NEXT_PUBLIC_SUPABASE_URL ?? "",
      "https://*.upstash.io",
    ].filter(Boolean).join(" "),
    "frame-src 'none'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "upgrade-insecure-requests",
  ].join("; ");

  /* ── 5. Response headers ────────────────────────────────────────────── */
  const securityHeaders: Record<string, string> = {
    // CSP with nonce
    "Content-Security-Policy":          csp,
    // Prevent clickjacking
    "X-Frame-Options":                  "DENY",
    // Prevent MIME sniffing
    "X-Content-Type-Options":           "nosniff",
    // Referrer — don't leak full URL to third parties
    "Referrer-Policy":                  "strict-origin-when-cross-origin",
    // Disable browser features we don't use
    "Permissions-Policy":               "camera=(), microphone=(), geolocation=()",
    // HSTS — 1 year, include subdomains
    "Strict-Transport-Security":        "max-age=31536000; includeSubDomains",
    // Tracing
    "X-Request-Id":                     requestId,
    // Remove the "powered by" header for security through obscurity
    "X-Powered-By":                     "",
  };

  Object.entries(securityHeaders).forEach(([key, value]) => {
    if (value) response.headers.set(key, value);
    else response.headers.delete(key);
  });

  return response;
}

/* ── Route matching ─────────────────────────────────────────────────────── */
export const config = {
  matcher: [
    /*
     * Match all request paths EXCEPT:
     *   - _next/static  (static files)
     *   - _next/image   (image optimisation)
     *   - favicon.ico, robots.txt, sitemap.xml
     */
    "/((?!_next/static|_next/image|favicon\\.ico|robots\\.txt|sitemap\\.xml).*)",
  ],
};
