import "server-only";
import { unstable_cache } from "next/cache";
import type { RegionData, TradingFloorResult } from "@/types/tradingFloor";

const REVALIDATE = 21_600;

const STATIC_FALLBACK: RegionData[] = [
  {
    region: "kenya_eastafrica",
    label: "Kenya & East Africa",
    shortLabel: "Kenya · EA",
    fetchedAt: new Date().toISOString(),
    headline: "CBK maintains benchmark rate as inflation eases toward target band",
    headlineUrl: "https://www.centralbank.go.ke",
    source: "Central Bank of Kenya",
    indices: [
      { symbol:"NSE20", name:"NSE 20 Share Index", country:"Kenya", countryFlag:"🇰🇪", price:"1,847.30", change:"+7.40", changePct:"+0.40%", direction:"up", currency:"KES", lastUpdated:"Indicative" },
      { symbol:"NASI", name:"NSE All Share (NASI)", country:"Kenya", countryFlag:"🇰🇪", price:"104.52", change:"+0.31", changePct:"+0.30%", direction:"up", currency:"KES", lastUpdated:"Indicative" },
      { symbol:"DSE", name:"DSE All Share Index", country:"Tanzania", countryFlag:"🇹🇿", price:"2,106.80", change:"-4.20", changePct:"-0.20%", direction:"down", currency:"TZS", lastUpdated:"Indicative" },
      { symbol:"USE", name:"USE All Share Index", country:"Uganda", countryFlag:"🇺🇬", price:"1,043.00", change:"+2.10", changePct:"+0.20%", direction:"up", currency:"UGX", lastUpdated:"Indicative" },
      { symbol:"RSE", name:"RSE All Share Index", country:"Rwanda", countryFlag:"🇷🇼", price:"136.40", change:"0.00", changePct:"0.00%", direction:"flat", currency:"RWF", lastUpdated:"Indicative" },
    ],
  },
  {
    region: "africa",
    label: "Africa",
    shortLabel: "Africa",
    fetchedAt: new Date().toISOString(),
    headline: "JSE gains as commodity prices stabilise; Nigerian equities lead African markets",
    headlineUrl: "https://www.jse.co.za",
    source: "JSE / African Markets",
    indices: [
      { symbol:"JSE", name:"JSE All Share", country:"South Africa", countryFlag:"🇿🇦", price:"81,240", change:"+320", changePct:"+0.40%", direction:"up", currency:"ZAR", lastUpdated:"Indicative" },
      { symbol:"EGX30", name:"EGX 30", country:"Egypt", countryFlag:"🇪🇬", price:"24,876", change:"+112", changePct:"+0.45%", direction:"up", currency:"EGP", lastUpdated:"Indicative" },
      { symbol:"NGX", name:"NGX All Share", country:"Nigeria", countryFlag:"🇳🇬", price:"97,430", change:"+580", changePct:"+0.60%", direction:"up", currency:"NGN", lastUpdated:"Indicative" },
      { symbol:"GSE", name:"GSE Composite", country:"Ghana", countryFlag:"🇬🇭", price:"4,180", change:"-22", changePct:"-0.52%", direction:"down", currency:"GHS", lastUpdated:"Indicative" },
      { symbol:"BRVM", name:"BRVM Composite", country:"West Africa", countryFlag:"🌍", price:"243.80", change:"+1.10", changePct:"+0.45%", direction:"up", currency:"XOF", lastUpdated:"Indicative" },
      { symbol:"LuSE", name:"LuSE All Share", country:"Zambia", countryFlag:"🇿🇲", price:"10,240", change:"+45", changePct:"+0.44%", direction:"up", currency:"ZMW", lastUpdated:"Indicative" },
    ],
  },
  {
    region: "europe",
    label: "Europe",
    shortLabel: "Europe",
    fetchedAt: new Date().toISOString(),
    headline: "ECB holds rates as eurozone inflation approaches 2% target; markets respond positively",
    headlineUrl: "https://www.ecb.europa.eu",
    source: "European Central Bank / Reuters",
    indices: [
      { symbol:"UKX", name:"FTSE 100", country:"UK", countryFlag:"🇬🇧", price:"8,420.30", change:"+34.20", changePct:"+0.41%", direction:"up", currency:"GBP", lastUpdated:"Indicative" },
      { symbol:"DAX", name:"DAX 40", country:"Germany", countryFlag:"🇩🇪", price:"18,734.50", change:"+112.30", changePct:"+0.60%", direction:"up", currency:"EUR", lastUpdated:"Indicative" },
      { symbol:"CAC40", name:"CAC 40", country:"France", countryFlag:"🇫🇷", price:"8,012.40", change:"-18.60", changePct:"-0.23%", direction:"down", currency:"EUR", lastUpdated:"Indicative" },
      { symbol:"STOXX50", name:"EURO STOXX 50", country:"Eurozone", countryFlag:"🇪🇺", price:"5,041.20", change:"+22.40", changePct:"+0.45%", direction:"up", currency:"EUR", lastUpdated:"Indicative" },
      { symbol:"SMI", name:"Swiss Market Index", country:"Switzerland", countryFlag:"🇨🇭", price:"11,842.00", change:"+56.30", changePct:"+0.48%", direction:"up", currency:"CHF", lastUpdated:"Indicative" },
      { symbol:"IBEX", name:"IBEX 35", country:"Spain", countryFlag:"🇪🇸", price:"11,240.30", change:"+78.40", changePct:"+0.70%", direction:"up", currency:"EUR", lastUpdated:"Indicative" },
      { symbol:"FTSEMIB", name:"FTSE MIB", country:"Italy", countryFlag:"🇮🇹", price:"34,120.00", change:"+142.00", changePct:"+0.42%", direction:"up", currency:"EUR", lastUpdated:"Indicative" },
      { symbol:"AEX", name:"AEX Index", country:"Netherlands", countryFlag:"🇳🇱", price:"876.40", change:"+4.20", changePct:"+0.48%", direction:"up", currency:"EUR", lastUpdated:"Indicative" },
      { symbol:"OMXS30", name:"OMX Stockholm 30", country:"Sweden", countryFlag:"🇸🇪", price:"2,543.00", change:"+12.40", changePct:"+0.49%", direction:"up", currency:"SEK", lastUpdated:"Indicative" },
      { symbol:"PSI20", name:"PSI 20", country:"Portugal", countryFlag:"🇵🇹", price:"6,820.00", change:"+28.40", changePct:"+0.42%", direction:"up", currency:"EUR", lastUpdated:"Indicative" },
    ],
  },
  {
    region: "north_america",
    label: "North America",
    shortLabel: "N. America",
    fetchedAt: new Date().toISOString(),
    headline: "Fed signals prolonged pause; S&P 500 holds near record highs on strong earnings season",
    headlineUrl: "https://www.federalreserve.gov",
    source: "Federal Reserve / Bloomberg",
    indices: [
      { symbol:"SPX", name:"S&P 500", country:"USA", countryFlag:"🇺🇸", price:"5,304.72", change:"+18.42", changePct:"+0.35%", direction:"up", currency:"USD", lastUpdated:"Indicative" },
      { symbol:"NDX", name:"NASDAQ Composite", country:"USA", countryFlag:"🇺🇸", price:"16,742.39", change:"+82.34", changePct:"+0.49%", direction:"up", currency:"USD", lastUpdated:"Indicative" },
      { symbol:"DJI", name:"Dow Jones Industrial", country:"USA", countryFlag:"🇺🇸", price:"39,134.86", change:"-42.77", changePct:"-0.11%", direction:"down", currency:"USD", lastUpdated:"Indicative" },
      { symbol:"RUT", name:"Russell 2000", country:"USA", countryFlag:"🇺🇸", price:"2,070.34", change:"+12.40", changePct:"+0.60%", direction:"up", currency:"USD", lastUpdated:"Indicative" },
      { symbol:"TSX", name:"S&P/TSX Composite", country:"Canada", countryFlag:"🇨🇦", price:"22,048.00", change:"+134.20", changePct:"+0.61%", direction:"up", currency:"CAD", lastUpdated:"Indicative" },
      { symbol:"IPC", name:"IPC BMV Index", country:"Mexico", countryFlag:"🇲🇽", price:"52,840.00", change:"-210.00", changePct:"-0.40%", direction:"down", currency:"MXN", lastUpdated:"Indicative" },
    ],
  },
  {
    region: "asia_pacific",
    label: "Asia Pacific",
    shortLabel: "Asia Pacific",
    fetchedAt: new Date().toISOString(),
    headline: "Bank of Japan holds policy steady; Asian markets mixed on China PMI data",
    headlineUrl: "https://www.boj.or.jp",
    source: "Bank of Japan / Reuters",
    indices: [
      { symbol:"N225", name:"Nikkei 225", country:"Japan", countryFlag:"🇯🇵", price:"38,646.11", change:"+304.75", changePct:"+0.80%", direction:"up", currency:"JPY", lastUpdated:"Indicative" },
      { symbol:"HSI", name:"Hang Seng Index", country:"Hong Kong", countryFlag:"🇭🇰", price:"17,234.50", change:"-82.30", changePct:"-0.48%", direction:"down", currency:"HKD", lastUpdated:"Indicative" },
      { symbol:"SHCOMP", name:"Shanghai Composite", country:"China", countryFlag:"🇨🇳", price:"3,089.26", change:"+14.42", changePct:"+0.47%", direction:"up", currency:"CNY", lastUpdated:"Indicative" },
      { symbol:"SENSEX", name:"BSE Sensex", country:"India", countryFlag:"🇮🇳", price:"73,428.30", change:"+312.40", changePct:"+0.43%", direction:"up", currency:"INR", lastUpdated:"Indicative" },
      { symbol:"NIFTY", name:"Nifty 50", country:"India", countryFlag:"🇮🇳", price:"22,302.50", change:"+98.20", changePct:"+0.44%", direction:"up", currency:"INR", lastUpdated:"Indicative" },
      { symbol:"ASX200", name:"ASX 200", country:"Australia", countryFlag:"🇦🇺", price:"7,843.40", change:"+34.20", changePct:"+0.44%", direction:"up", currency:"AUD", lastUpdated:"Indicative" },
      { symbol:"KOSPI", name:"KOSPI", country:"South Korea", countryFlag:"🇰🇷", price:"2,680.40", change:"+22.30", changePct:"+0.84%", direction:"up", currency:"KRW", lastUpdated:"Indicative" },
      { symbol:"STI", name:"Straits Times Index", country:"Singapore", countryFlag:"🇸🇬", price:"3,340.20", change:"+8.40", changePct:"+0.25%", direction:"up", currency:"SGD", lastUpdated:"Indicative" },
      { symbol:"TWSE", name:"Taiwan Weighted", country:"Taiwan", countryFlag:"🇹🇼", price:"20,422.00", change:"+188.40", changePct:"+0.93%", direction:"up", currency:"TWD", lastUpdated:"Indicative" },
      { symbol:"SET", name:"SET Index", country:"Thailand", countryFlag:"🇹🇭", price:"1,328.40", change:"-4.20", changePct:"-0.31%", direction:"down", currency:"THB", lastUpdated:"Indicative" },
      { symbol:"KLCI", name:"FTSE Bursa KLCI", country:"Malaysia", countryFlag:"🇲🇾", price:"1,547.30", change:"+6.80", changePct:"+0.44%", direction:"up", currency:"MYR", lastUpdated:"Indicative" },
      { symbol:"NZX50", name:"NZX 50", country:"New Zealand", countryFlag:"🇳🇿", price:"11,842.00", change:"+42.30", changePct:"+0.36%", direction:"up", currency:"NZD", lastUpdated:"Indicative" },
    ],
  },
  {
    region: "middle_east",
    label: "Middle East",
    shortLabel: "Middle East",
    fetchedAt: new Date().toISOString(),
    headline: "Saudi Tadawul gains on oil price recovery; Gulf markets broadly positive",
    headlineUrl: "https://www.saudiexchange.sa",
    source: "Saudi Exchange / Gulf News",
    indices: [
      { symbol:"TASI", name:"Tadawul All Share", country:"Saudi Arabia", countryFlag:"🇸🇦", price:"11,842.30", change:"+78.40", changePct:"+0.67%", direction:"up", currency:"SAR", lastUpdated:"Indicative" },
      { symbol:"DFM", name:"DFM General Index", country:"UAE (Dubai)", countryFlag:"🇦🇪", price:"4,312.40", change:"+22.30", changePct:"+0.52%", direction:"up", currency:"AED", lastUpdated:"Indicative" },
      { symbol:"ADX", name:"ADX General Index", country:"UAE (Abu Dhabi)", countryFlag:"🇦🇪", price:"9,420.00", change:"+34.20", changePct:"+0.36%", direction:"up", currency:"AED", lastUpdated:"Indicative" },
      { symbol:"QSE", name:"QSE General Index", country:"Qatar", countryFlag:"🇶🇦", price:"10,240.30", change:"-28.40", changePct:"-0.28%", direction:"down", currency:"QAR", lastUpdated:"Indicative" },
      { symbol:"BHB", name:"Bahrain All Share", country:"Bahrain", countryFlag:"🇧🇭", price:"1,842.00", change:"+4.20", changePct:"+0.23%", direction:"up", currency:"BHD", lastUpdated:"Indicative" },
      { symbol:"MSM30", name:"MSM 30 Index", country:"Oman", countryFlag:"🇴🇲", price:"4,620.00", change:"+18.40", changePct:"+0.40%", direction:"up", currency:"OMR", lastUpdated:"Indicative" },
      { symbol:"KSE", name:"Kuwait All Share", country:"Kuwait", countryFlag:"🇰🇼", price:"7,842.00", change:"+22.40", changePct:"+0.29%", direction:"up", currency:"KWD", lastUpdated:"Indicative" },
    ],
  },
  {
    region: "latin_america",
    label: "Latin America",
    shortLabel: "Latin America",
    fetchedAt
